//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageDetaiil
    {
        public long id { get; set; }
        public string imagename { get; set; }
        public string imagepath { get; set; }
        public Nullable<long> uplodedby { get; set; }
    }
}
